### ISSUE TITLE
CN0 on tracking

### ISSUE THREAD

**Issue by fabriciocscte** [TMBOC/SoftGNSS#1]
Have you tried enable the option that allows to show CN0 in the tracking ?
There is an option on initSettings.m, but It seems not works.

**Comment by TMBOC** [comment]
Hello Fabricio,

Yes, I tried once but failed. I will fix it shortly.
Thanks for the report.

Best Regards

Xin

2018-04-16 21:51 GMT+08:00 Fabrício Costa <notifications@github.com>:

**Comment by TMBOC** [comment]
Now CN0 should be OK.
