### ISSUE TITLE
Data format of raw data file

### ISSUE THREAD

**Issue by gnsssdr** [TMBOC/SoftGNSS#2]
Can you explain what format used in your raw data files?

**Comment by Imtiaz08** [comment]
.bin, and .dat files

**Comment by gnsssdr** [comment]
I can't download data from your links, is it possible to provide another link for it?

**Comment by unalfaruk** [comment]
Hey @gnsssdr,

Try the link below:
[Google Drive, IF GNSS Signals](https://drive.google.com/drive/folders/1oPOW9idULvt-I1ZICS3jVAkXVNW0q3eU?usp=sharing)

**Comment by gnsssdr** [comment]
> Hey @gnsssdr,
> 
> Try the link below: [Google Drive, IF GNSS Signals](https://drive.google.com/drive/folders/1oPOW9idULvt-I1ZICS3jVAkXVNW0q3eU?usp=sharing)
> 
> You will find "gnss0.bin" and "gnsa14.bin" files in the folder.

Thank you so much

**Comment by Imtiaz08** [comment]
Hi, I am very thankful to you for providing the data files. However, I
would like to know the specifications of the files as I won't be able to
process them without it.

Can you please tell me what is the IF, sampling frequency, number of
milliseconds to process and data type in these files?

**Comment by TMBOC** [comment]
Sorry for the late response and thank you all @Imtiaz08  @unalfaruk . The two data files were collected using [SiGe GN3S Sampler v2](https://www.sparkfun.com/products/retired/8238) (OOP though...) and therefore,

|File Name   | Data Length in Seconds | I\/Q Format (as in initSettings.m)             |
| ----------  | -----------------------  | ---------------------------------------- |
| gnss0.bin   | 60.5                                  | 8 bit I/Q samples I0,Q0,I1,Q1,I2,Q2,I3/Q3 |
| gnsa14.bin | 40                                     | 8 bit I/Q samples I0,Q0,I1,Q1,I2,Q2,I3/Q3 |
